name: Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    name: Test
    steps:
    - name: 1 - Checkout branch
      uses: actions/checkout@v2

    - name: 2 - Get latest CMake
      # Using 'latest' branch, the latest CMake is installed.
      uses: lukka/get-cmake@latest

    - name: 3 - Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: 4 - Run tests
      run: |
        cd build
        ./tests
